// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package adminclient

import (
	"context"

	"github.com/DolphinDong/ops-admin/common/rpc/pb/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckPermissionReq = admin.CheckPermissionReq
	CheckPermissionRes = admin.CheckPermissionRes
	CheckTokenReq      = admin.CheckTokenReq
	CheckTokenRes      = admin.CheckTokenRes
	LoginReq           = admin.LoginReq
	LoginRes           = admin.LoginRes

	Admin interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
		CheckToken(ctx context.Context, in *CheckTokenReq, opts ...grpc.CallOption) (*CheckTokenRes, error)
		CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionRes, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAdmin) CheckToken(ctx context.Context, in *CheckTokenReq, opts ...grpc.CallOption) (*CheckTokenRes, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CheckToken(ctx, in, opts...)
}

func (m *defaultAdmin) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionRes, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CheckPermission(ctx, in, opts...)
}
